// Custom fantasy scoring rules for the league, transcribed from the
// commissioner tool's "Scoring Rules" export. Kept as static data rather
// than a Supabase table -- these are league-defined settings, not NFL
// stats pulled from nflverse, and change rarely if ever.
//
// Every group here is "universal": the events it lists can be scored for
// ANY roster player who records them (a TE who throws a TD pass still
// earns the QB group's passing-TD points), NOT just the position the
// group is nominally named after -- that's the whole point of tagging
// them. The three EXCEPTIONS are Coach, ST, and DEF: those are tied to
// their own dedicated roster slots and never apply to anyone else.
//
// Numbers transcribed from a screenshot of a dense table -- double-check
// the exact figures against the league's own rules page before treating
// this as authoritative.

export const RULE_GROUPS = [
  {
    tag: 'Coach',
    title: 'Rules for Coach',
    appliesTo: ['Head Coach'],
    independent: true,
    rules: [
      { event: 'Point Differential', range: '-199-199', points: '0.3 points each' },
      { event: 'Games Won', range: '1-1', points: '7' },
      { event: 'Games Lost', range: '1-1', points: '3' },
      { event: 'Games Tied', range: '1-1', points: '5' },
    ],
  },
  {
    tag: 'QB',
    title: 'Rules for QB',
    appliesTo: ['QB'],
    rules: [
      { event: 'Number of Passing TDs', range: '1-99', points: '2 points each' },
      { event: 'Length of Passing TD', range: '0-9', points: '1' },
      { event: 'Length of Passing TD', range: '10-19', points: '2' },
      { event: 'Length of Passing TD', range: '20-39', points: '4' },
      { event: 'Length of Passing TD', range: '40-59', points: '6' },
      { event: 'Length of Passing TD', range: '60-79', points: '8' },
      { event: 'Length of Passing TD', range: '80-98', points: '10' },
      { event: 'Length of Passing TD', range: '99-100', points: '12' },
      { event: 'Passing Yards', range: '-999-999', points: '0.05 points each' },
      { event: 'Pass Completions', range: '1-999', points: '0.3 points each' },
      { event: 'Pass Incompletions', range: '1-999', points: '-0.4 points each' },
      { event: 'Pass Interceptions Thrown', range: '1-10', points: '-4 points each' },
      { event: 'Number of Interceptions Thrown Returned for a TD', range: '1-10', points: '-4 points each' },
      { event: 'Length of Interception Thrown Returned for a TD', range: '0-110', points: '-0.04 points each' },
      { event: 'QB Sacked Yardage', range: '0-999', points: '-0.2 points each' },
      { event: 'Long Passing Plays of 20+ Yards', range: '1-99', points: '2 points each' },
      { event: 'Long Passing Plays of 40+ Yards', range: '1-99', points: '3 points each' },
      { event: 'Passing 2 Pointers', range: '1-10', points: '2 points each' },
    ],
  },
  {
    tag: 'Rush/Rec',
    title: 'Rules for QB, RB, FB, WR, TE',
    appliesTo: ['QB', 'RB', 'FB', 'WR', 'TE'],
    rules: [
      { event: 'Number of Rushing TDs', range: '1-10', points: '2 points each' },
      { event: 'Length of Rushing TD', range: '0-9', points: '1' },
      { event: 'Length of Rushing TD', range: '10-19', points: '2' },
      { event: 'Length of Rushing TD', range: '20-39', points: '4' },
      { event: 'Length of Rushing TD', range: '40-59', points: '6' },
      { event: 'Length of Rushing TD', range: '60-79', points: '8' },
      { event: 'Length of Rushing TD', range: '80-98', points: '10' },
      { event: 'Length of Rushing TD', range: '99-100', points: '12' },
      { event: 'Rushing Yards', range: '-50-999', points: '0.1 points each' },
      { event: 'Long Rushing Plays of 20+ Yards', range: '1-99', points: '2 points each' },
      { event: 'Long Rushing Plays of 40+ Yards', range: '1-99', points: '3 points each' },
      { event: 'Rushing 2 Pointers', range: '1-10', points: '2 points each' },
      { event: 'Number of Receiving TDs', range: '1-10', points: '2 points each' },
      { event: 'Length of Receiving TD', range: '0-9', points: '1' },
      { event: 'Length of Receiving TD', range: '10-19', points: '2' },
      { event: 'Length of Receiving TD', range: '20-39', points: '4' },
      { event: 'Length of Receiving TD', range: '40-59', points: '6' },
      { event: 'Length of Receiving TD', range: '60-79', points: '8' },
      { event: 'Length of Receiving TD', range: '80-98', points: '10' },
      { event: 'Length of Receiving TD', range: '99-100', points: '12' },
      { event: 'Receiving Yards', range: '-50-999', points: '0.1 points each' },
      { event: 'Receptions', range: '1-99', points: '1 point each' },
      { event: 'Targets', range: '0-99', points: '-0.5 points each', test: 'Test (Warning)' },
      { event: 'Long Receptions of 20+ Yards', range: '1-99', points: '1 point each' },
      { event: 'Long Receptions of 40+ Yards', range: '1-99', points: '2 points each' },
      { event: 'Receiving 2 Pointers', range: '1-10', points: '2 points each' },
    ],
  },
  {
    tag: 'Fumbles',
    title: 'Rules for QB, RB, FB, WR, TE, PK, PN, DT, LB, CB, S',
    appliesTo: ['QB', 'RB', 'FB', 'WR', 'TE', 'PK', 'PN', 'DT', 'LB', 'CB', 'S'],
    rules: [
      { event: 'Fumbles', range: '1-99', points: '-2 points each' },
      { event: 'Fumbles Lost (to Opponent)', range: '1-99', points: '-3 points each' },
      { event: 'Number of Fumbles Lost Returned for a TD', range: '1-10', points: '-6 points each' },
      { event: 'Length of Lost Fumble Returned for a TD', range: '0-110', points: '-0.04 points each' },
      { event: 'Number of Own Fumble Recoveries', range: '1-99', points: '2 points each' },
      { event: 'Own Fumble Recovery Yardage', range: '0-999', points: '0.1 points each' },
      { event: 'Penalty Yards', range: '1-999', points: '-0.2 points each' },
    ],
  },
  {
    tag: 'Returns',
    title: 'Rules for RB, FB, WR, TE, CB, S, LB',
    appliesTo: ['RB', 'FB', 'WR', 'TE', 'CB', 'S', 'LB'],
    rules: [
      { event: 'Length of Punt Return TD', range: '0-39', points: '6' },
      { event: 'Length of Punt Return TD', range: '40-59', points: '8' },
      { event: 'Length of Punt Return TD', range: '60-79', points: '10' },
      { event: 'Length of Punt Return TD', range: '80-98', points: '12' },
      { event: 'Length of Punt Return TD', range: '99-100', points: '15' },
      { event: 'Punt Return Yards', range: '-50-999', points: '0.2 points each' },
      { event: 'Length of Kickoff Return TD', range: '0-49', points: '8' },
      { event: 'Length of Kickoff Return TD', range: '50-69', points: '10' },
      { event: 'Length of Kickoff Return TD', range: '70-89', points: '12' },
      { event: 'Length of Kickoff Return TD', range: '90-110', points: '15' },
      { event: 'Kickoff Return Yards', range: '-50-999', points: '0.1 points each' },
    ],
  },
  {
    tag: 'Efficiency',
    title: 'Rules for FB, TE',
    appliesTo: ['FB', 'TE'],
    rules: [
      { event: 'Average Yards per Pass Completion', range: '-99-100', points: '0.1 points each' },
      { event: 'Average Yards per Rush', range: '-99-100', points: '1 point each' },
      { event: 'Rush Attempts', range: '1-99', points: '0.5 points each' },
      { event: 'Average Yards per Reception', range: '-99-100', points: '0.5 points each' },
    ],
  },
  {
    tag: 'Kicking',
    title: 'Rules for PK',
    appliesTo: ['PK'],
    rules: [
      { event: 'Length of Field Goal Made', range: '0-29', points: '2' },
      { event: 'Length of Field Goal Made', range: '30-39', points: '3' },
      { event: 'Length of Field Goal Made', range: '40-44', points: '4' },
      { event: 'Length of Field Goal Made', range: '45-49', points: '4.5' },
      { event: 'Length of Field Goal Made', range: '50-54', points: '5' },
      { event: 'Length of Field Goal Made', range: '55-59', points: '5.5' },
      { event: 'Length of Field Goal Made', range: '60-64', points: '6' },
      { event: 'Length of Field Goal Made', range: '65-69', points: '7' },
      { event: 'Length of Field Goal Made', range: '70-74', points: '8' },
      { event: 'Length of Field Goal Made', range: '75-79', points: '9' },
      { event: 'Length of Field Goal Made', range: '80-99', points: '10' },
      { event: 'Length of Missed Field Goal', range: '0-29', points: '-3' },
      { event: 'Length of Missed Field Goal', range: '30-49', points: '-2' },
      { event: 'Length of Missed Field Goal', range: '50-99', points: '-1' },
      { event: 'Field Goals Had Blocked', range: '1-10', points: '-2 points each' },
      { event: 'Extra Points', range: '1-10', points: '0.5 points each' },
      { event: 'Extra Points Missed', range: '1-10', points: '-4 points each' },
      { event: 'Extra Points Had Blocked', range: '1-10', points: '-2 points each' },
    ],
  },
  {
    tag: 'Punting',
    title: 'Rules for PN',
    appliesTo: ['PN'],
    rules: [
      { event: 'Punt Yards', range: '-999-0', points: '-5' },
      { event: 'Punt Yards', range: '1-100', points: '1' },
      { event: 'Punt Yards', range: '101-200', points: '2' },
      { event: 'Punt Yards', range: '201-300', points: '3' },
      { event: 'Punt Yards', range: '301-400', points: '4' },
      { event: 'Punt Yards', range: '401-500', points: '6' },
      { event: 'Punt Yards', range: '501-600', points: '10' },
      { event: 'Punt Yards', range: '601-999', points: '15' },
      { event: 'Average Yards per Punt', range: '0-39.9', points: '0 points for 0, and then 0.05 point for every 1 thereafter' },
      { event: 'Average Yards per Punt', range: '40-100', points: '2 points for 40, and then 0.04 point for every 0.1 thereafter' },
      { event: 'Points Inside 20', range: '1-20', points: '2.5 points each' },
      { event: 'Points Had Blocked', range: '1-10', points: '-4 points each' },
    ],
  },
  {
    tag: 'IDP Defense',
    title: 'Rules for DT, DE, LB, CB, S',
    appliesTo: ['DT', 'DE', 'LB', 'CB', 'S'],
    rules: [
      { event: 'Fumble Recoveries (from Opponent)', range: '1-99', points: '3 points each' },
      { event: 'Opponent Fumble Recovery Yards', range: '-50-999', points: '0.3 points each' },
      { event: 'Forced Fumbles', range: '1-99', points: '3 points each' },
      { event: 'Interceptions Caught', range: '1-10', points: '5 points each' },
      { event: 'Interception Return Yards', range: '-50-999', points: '0.3 points each' },
      { event: 'Passes Deflected', range: '1-99', points: '4 points each' },
      { event: 'Blocked Field Goals', range: '1-10', points: '4 points each' },
      { event: 'Blocked Punts', range: '1-10', points: '4 points each' },
      { event: 'Blocked Extra Points', range: '1-10', points: '4 points each' },
      { event: 'Tackles', range: '0-99', points: '1.2 points each' },
      { event: 'Assists', range: '0-99', points: '0.6 points each' },
      { event: 'Sacked a QB', range: '0-25', points: '2 points each' },
      { event: 'Sacked a QB Yardage', range: '0-100', points: '0.3 points each' },
      { event: 'Tackles for a Loss', range: '1-10', points: '3 points each' },
      { event: 'Safeties', range: '0-10', points: '2 points each' },
      { event: 'Number of Defensive TDs', range: '1-10', points: '5 points each' },
      { event: 'Length of Defensive TD', range: '0-110', points: '0.32 points each' },
      { event: 'Safeties for 1 Point', range: '1-10', points: '10 points each' },
    ],
  },
  {
    tag: 'ST',
    title: 'Rules for ST',
    subtitle: "ST is the team's offense.",
    appliesTo: ['ST'],
    independent: true,
    rules: [
      { event: 'Number of Passing TDs', range: '1-99', points: '1.5 points each' },
      { event: 'Passing Yards', range: '-50-999', points: '0.01 points each' },
      { event: 'QB Sacked', range: '1-99', points: '-1 point each' },
      { event: 'Number of Rushing TDs', range: '1-99', points: '1.5 points each' },
      { event: 'Rushing Yards', range: '-50-999', points: '0.02 points each' },
      { event: 'Number of Field Goals Made', range: '1-99', points: '0.5 points each' },
      { event: 'Fumbles Lost on Offense', range: '1-99', points: '-1.5 points each' },
      { event: 'Opponent Interceptions Caught', range: '1-99', points: '-1.5 points each' },
      { event: 'Opponent Number of Defensive TDs', range: '1-99', points: '-0.5 points each' },
      { event: 'Offensive Points Only', range: '0-6', points: '-3' },
      { event: 'First Downs', range: '1-99', points: '0.1 points each' },
    ],
  },
  {
    tag: 'DEF',
    title: 'Rules for DEF',
    appliesTo: ['DEF'],
    independent: true,
    rules: [
      { event: 'Opponent Number of Passing TDs', range: '1-99', points: '-1 point each' },
      { event: 'Opponent Pass Incompletions', range: '1-99', points: '0.2 points each' },
      { event: 'Opponent Number of Rushing TDs', range: '1-99', points: '-1 point each' },
      { event: 'Opponent Punts', range: '1-99', points: '1.5 points each' },
      { event: 'Fumble Recoveries on Defense', range: '1-10', points: '3 points each' },
      { event: 'Interceptions Caught', range: '1-10', points: '3 points each' },
      { event: 'Blocked Field Goals', range: '1-10', points: '4 points each' },
      { event: 'Blocked Punts', range: '1-10', points: '4 points each' },
      { event: 'Blocked Extra Points', range: '1-10', points: '2 points each' },
      { event: 'Sacked a QB', range: '1-25', points: '2 points each' },
      { event: 'Quarterback Hits', range: '1-99', points: '0.3 points each' },
      { event: 'Safeties', range: '1-10', points: '5 points each' },
      { event: 'Offensive Points Against', range: '0-9', points: '5', test: 'Test (Warning)' },
      { event: 'Passing Yards Allowed', range: '0-99', points: '5' },
      { event: 'Passing Yards Allowed', range: '100-999', points: '0.01 points each' },
      { event: 'Rushing Yards Allowed', range: '0-99', points: '5' },
      { event: 'Rushing Yards Allowed', range: '1-999', points: '-0.02 points each' },
      { event: 'Number of Defensive TDs', range: '1-10', points: '6 points each' },
      { event: 'Opponent Penalty First Downs', range: '1-99', points: '-1 point each' },
      { event: 'Opponent Fourth Downs Failed', range: '1-99', points: '1 point each' },
    ],
  },
]

// Every group except Coach/ST/DEF scores for whichever roster player
// actually recorded the event, regardless of their primary position.
export const UNIVERSAL_TAGS = RULE_GROUPS.filter((g) => !g.independent).map((g) => g.tag)
export const INDEPENDENT_TAGS = RULE_GROUPS.filter((g) => g.independent).map((g) => g.tag)

// Legal starting lineup composition.
export const STARTING_LINEUP = [
  { slot: 'Head Coach', count: 1 },
  { slot: 'Defense (DEF)', count: 1 },
  { slot: 'Special Teams (ST)', count: 1 },
  { slot: 'QB', count: 1 },
  { slot: 'PK', count: 1 },
  { slot: 'PN', count: 1 },
  { slot: 'Any IDP or skill position', count: 10 },
]
export const IR_SLOTS = 2
export const RESERVE_SLOTS = 5
