// Custom fantasy scoring rules for the league, transcribed from the
// commissioner tool's "Scoring Rules" export. Kept as static data rather
// than a Supabase table -- these are league-defined settings, not NFL
// stats pulled from nflverse, and change rarely if ever.
//
// Each group's rules apply to whichever roster player actually recorded
// the event -- NOT necessarily the specific position the group used to be
// drawn up around -- but each group has its OWN eligible-position list
// (see each group's `subtitle`), not a single universal list. Head Coach,
// Offensive Coordinator (ST), and Defensive Coordinator (DEF) are the
// exceptions that apply to a dedicated roster slot only, never to a
// player directly (see `independent` below).

export const RULE_GROUPS = [
  {
    tag: 'Head Coach',
    independent: true,
    rules: [
      { event: 'Point Differential', range: '-199-199', points: '0.3 points each' },
      { event: 'Games Won', range: '1-1', points: '7' },
      { event: 'Games Lost', range: '1-1', points: '3' },
      { event: 'Games Tied', range: '1-1', points: '5' },
    ],
  },
  {
    tag: 'Passing',
    rules: [
      { event: 'Number of Passing TDs', range: '1-99', points: '2 points each' },
      { event: 'Length of Passing TD', range: '0-9', points: '1' },
      { event: 'Length of Passing TD', range: '10-19', points: '2' },
      { event: 'Length of Passing TD', range: '20-39', points: '4' },
      { event: 'Length of Passing TD', range: '40-59', points: '6' },
      { event: 'Length of Passing TD', range: '60-79', points: '8' },
      { event: 'Length of Passing TD', range: '80-98', points: '10' },
      { event: 'Length of Passing TD', range: '99-100', points: '12' },
      { event: 'Passing Yards', range: '-999-999', points: '0.05 points each' },
      { event: 'Pass Completions', range: '1-999', points: '0.3 points each' },
      { event: 'Pass Incompletions', range: '1-999', points: '-0.4 points each' },
      { event: 'Pass Interceptions Thrown', range: '1-10', points: '-4 points each' },
      { event: 'Number of Interceptions Thrown Returned for a TD', range: '1-10', points: '-4 points each' },
      { event: 'Length of Interception Thrown Returned for a TD', range: '0-110', points: '-0.04 points each' },
      { event: 'QB Sacked Yardage', range: '0-999', points: '-0.2 points each' },
      { event: 'Long Passing Plays of 20+ Yards', range: '1-99', points: '2 points each' },
      { event: 'Long Passing Plays of 40+ Yards', range: '1-99', points: '3 points each' },
      { event: 'Passing 2 Pointers', range: '1-10', points: '2 points each' },
    ],
  },
  {
    tag: 'Rushing/Receiving',
    subtitle: 'Applies to QB, RB, FB, WR, TE.',
    rules: [
      { event: 'Number of Rushing TDs', range: '1-10', points: '2 points each' },
      { event: 'Length of Rushing TD', range: '0-9', points: '1' },
      { event: 'Length of Rushing TD', range: '10-19', points: '2' },
      { event: 'Length of Rushing TD', range: '20-39', points: '4' },
      { event: 'Length of Rushing TD', range: '40-59', points: '6' },
      { event: 'Length of Rushing TD', range: '60-79', points: '8' },
      { event: 'Length of Rushing TD', range: '80-98', points: '10' },
      { event: 'Length of Rushing TD', range: '99-100', points: '12' },
      { event: 'Rushing Yards', range: '-50-999', points: '0.1 points each' },
      { event: 'Long Rushing Plays of 20+ Yards', range: '1-99', points: '2 points each' },
      { event: 'Long Rushing Plays of 40+ Yards', range: '1-99', points: '3 points each' },
      { event: 'Rushing 2 Pointers', range: '1-10', points: '2 points each' },
      { event: 'Number of Receiving TDs', range: '1-10', points: '2 points each' },
      { event: 'Length of Receiving TD', range: '0-9', points: '1' },
      { event: 'Length of Receiving TD', range: '10-19', points: '2' },
      { event: 'Length of Receiving TD', range: '20-39', points: '4' },
      { event: 'Length of Receiving TD', range: '40-59', points: '6' },
      { event: 'Length of Receiving TD', range: '60-79', points: '8' },
      { event: 'Length of Receiving TD', range: '80-98', points: '10' },
      { event: 'Length of Receiving TD', range: '99-100', points: '12' },
      { event: 'Receiving Yards', range: '-50-999', points: '0.1 points each' },
      { event: 'Receptions', range: '1-99', points: '1 point each' },
      { event: 'Targets', range: '0-99', points: '-0.5 points each' },
      { event: 'Long Receptions of 20+ Yards', range: '1-99', points: '1 point each' },
      { event: 'Long Receptions of 40+ Yards', range: '1-99', points: '2 points each' },
      { event: 'Receiving 2 Pointers', range: '1-10', points: '2 points each' },
    ],
  },
  {
    tag: 'Fumbles and Fouls',
    subtitle: 'Applies to QB, RB, FB, WR, TE, PK, PN, DT, DE, LB, CB, S.',
    rules: [
      { event: 'Fumbles', range: '1-99', points: '-2 points each' },
      { event: 'Fumbles Lost (to Opponent)', range: '1-99', points: '-3 points each' },
      { event: 'Number of Fumbles Lost Returned for a TD', range: '1-10', points: '-6 points each' },
      { event: 'Length of Lost Fumble Returned for a TD', range: '0-110', points: '-0.04 points each' },
      { event: 'Number of Own Fumble Recoveries', range: '1-99', points: '2 points each' },
      { event: 'Own Fumble Recovery Yardage', range: '0-999', points: '0.1 points each' },
      { event: 'Penalty Yards', range: '1-999', points: '-0.2 points each' },
    ],
  },
  {
    tag: 'Returning',
    subtitle: 'Applies to RB, FB, WR, TE, CB, S, LB.',
    rules: [
      { event: 'Length of Punt Return TD', range: '0-39', points: '6' },
      { event: 'Length of Punt Return TD', range: '40-59', points: '8' },
      { event: 'Length of Punt Return TD', range: '60-79', points: '10' },
      { event: 'Length of Punt Return TD', range: '80-98', points: '12' },
      { event: 'Length of Punt Return TD', range: '99-110', points: '15' },
      { event: 'Punt Return Yards', range: '-50-999', points: '0.2 points each' },
      { event: 'Length of Kickoff Return TD', range: '0-49', points: '8' },
      { event: 'Length of Kickoff Return TD', range: '50-69', points: '10' },
      { event: 'Length of Kickoff Return TD', range: '70-89', points: '12' },
      { event: 'Length of Kickoff Return TD', range: '90-110', points: '15' },
      { event: 'Kickoff Return Yards', range: '-50-999', points: '0.1 points each' },
    ],
  },
  {
    tag: 'Blocking Bonus',
    subtitle: 'Applies to FB, TE.',
    rules: [
      { event: 'Average Yards per Pass Completion', range: '-99-100', points: '0.1 points each' },
      { event: 'Average Yards per Rush', range: '-99-100', points: '1 point each' },
      { event: 'Rush Attempts', range: '1-99', points: '0.5 points each' },
      { event: 'Average Yards per Reception', range: '-99-100', points: '0.5 points each' },
    ],
  },
  {
    tag: 'Kicking',
    rules: [
      { event: 'Length of Field Goal Made', range: '0-29', points: '2' },
      { event: 'Length of Field Goal Made', range: '30-39', points: '3' },
      { event: 'Length of Field Goal Made', range: '40-44', points: '4' },
      { event: 'Length of Field Goal Made', range: '45-49', points: '4.5' },
      { event: 'Length of Field Goal Made', range: '50-54', points: '5' },
      { event: 'Length of Field Goal Made', range: '55-59', points: '5.5' },
      { event: 'Length of Field Goal Made', range: '60-64', points: '6' },
      { event: 'Length of Field Goal Made', range: '65-69', points: '7' },
      { event: 'Length of Field Goal Made', range: '70-74', points: '8' },
      { event: 'Length of Field Goal Made', range: '75-79', points: '9' },
      { event: 'Length of Field Goal Made', range: '80-99', points: '10' },
      { event: 'Length of Missed Field Goal', range: '0-29', points: '-3' },
      { event: 'Length of Missed Field Goal', range: '30-49', points: '-2' },
      { event: 'Length of Missed Field Goal', range: '50-99', points: '-1' },
      { event: 'Field Goals Had Blocked', range: '1-10', points: '-2 points each' },
      { event: 'Extra Points', range: '1-10', points: '0.5 points each' },
      { event: 'Extra Points Missed', range: '1-10', points: '-4 points each' },
      { event: 'Extra Points Had Blocked', range: '1-10', points: '-2 points each' },
    ],
  },
  {
    tag: 'Punting',
    rules: [
      { event: 'Punt Yards', range: '-999-0', points: '-5' },
      { event: 'Punt Yards', range: '1-100', points: '1' },
      { event: 'Punt Yards', range: '101-200', points: '2' },
      { event: 'Punt Yards', range: '201-300', points: '3' },
      { event: 'Punt Yards', range: '301-400', points: '4' },
      { event: 'Punt Yards', range: '401-500', points: '6' },
      { event: 'Punt Yards', range: '501-600', points: '10' },
      { event: 'Punt Yards', range: '601-999', points: '15' },
      { event: 'Average Yards per Punt', range: '0-39.9', points: '0 points for 0, and then 0.05 point for every 1 thereafter' },
      { event: 'Average Yards per Punt', range: '40-100', points: '2 points for 40, and then 0.04 point for every 0.1 thereafter' },
      { event: 'Points Inside 20', range: '1-20', points: '2.5 points each' },
      { event: 'Points Had Blocked', range: '1-10', points: '-4 points each' },
    ],
  },
  {
    tag: 'Defense',
    subtitle: 'Applies to DT, DE, LB, CB, S.',
    rules: [
      { event: 'Fumble Recoveries (from Opponent)', range: '1-99', points: '3 points each' },
      { event: 'Opponent Fumble Recovery Yards', range: '-50-999', points: '0.3 points each' },
      { event: 'Forced Fumbles', range: '1-99', points: '3 points each' },
      { event: 'Interceptions Caught', range: '1-10', points: '5 points each' },
      { event: 'Interception Return Yards', range: '-50-999', points: '0.3 points each' },
      { event: 'Passes Defended', range: '1-99', points: '4 points each' },
      { event: 'Blocked Field Goals', range: '1-10', points: '4 points each' },
      { event: 'Blocked Punts', range: '1-10', points: '4 points each' },
      { event: 'Blocked Extra Points', range: '1-10', points: '4 points each' },
      { event: 'Tackles', range: '0-99', points: '1.2 points each' },
      { event: 'Assists', range: '0-99', points: '0.6 points each' },
      { event: 'Sacked a QB', range: '0-25', points: '2 points each' },
      { event: 'Sacked a QB Yardage', range: '0-100', points: '0.3 points each' },
      { event: 'Quarterback Hits', range: '1-10', points: '2 points each' },
      { event: 'Tackles for a Loss', range: '0-25', points: '3 points each' },
      { event: 'Safeties', range: '0-10', points: '2 points each' },
      { event: 'Number of Defensive TDs', range: '1-10', points: '5 points each' },
      { event: 'Length of Defensive TD', range: '0-110', points: '0.02 points each' },
      { event: 'Safeties for 1 Point', range: '1-10', points: '10 points each' },
    ],
  },
  {
    tag: 'Offensive Coordinator',
    subtitle: "The team's offense as a unit (ST).",
    independent: true,
    rules: [
      { event: 'Number of Passing TDs', range: '1-99', points: '1.5 points each' },
      { event: 'Passing Yards', range: '-50-999', points: '0.01 points each' },
      { event: 'QB Sacked', range: '1-99', points: '-1 point each' },
      { event: 'Number of Rushing TDs', range: '1-99', points: '1.5 points each' },
      { event: 'Rushing Yards', range: '-50-999', points: '0.02 points each' },
      { event: 'Number of Field Goals Made', range: '1-99', points: '0.5 points each' },
      { event: 'Fumbles Lost on Offense', range: '1-99', points: '-1.5 points each' },
      { event: 'Opponent Interceptions Caught', range: '1-99', points: '-1.5 points each' },
      { event: 'Opponent Quarterback Hits', range: '1-99', points: '-0.5 points each' },
      { event: 'Opponent Number of Defensive TDs', range: '1-99', points: '-4.5 points each' },
      { event: 'Offensive Points Only', range: '0-0', points: '-5' },
      { event: 'First Downs', range: '1-99', points: '0.1 points each' },
    ],
  },
  {
    tag: 'Defensive Coordinator',
    subtitle: "The team's defense as a unit (DEF).",
    independent: true,
    rules: [
      { event: 'Opponent Number of Passing TDs', range: '1-99', points: '-1 point each' },
      { event: 'Opponent Pass Incompletions', range: '1-99', points: '0.2 points each' },
      { event: 'Opponent Number of Rushing TDs', range: '1-99', points: '-1 point each' },
      { event: 'Opponent Punts', range: '1-99', points: '0.5 points each' },
      { event: 'Fumble Recoveries on Defense', range: '1-10', points: '3 points each' },
      { event: 'Interceptions Caught', range: '1-10', points: '3 points each' },
      { event: 'Blocked Field Goals', range: '1-10', points: '4 points each' },
      { event: 'Blocked Punts', range: '1-10', points: '4 points each' },
      { event: 'Blocked Extra Points', range: '1-10', points: '2 points each' },
      { event: 'Sacked a QB', range: '1-25', points: '1.5 points each' },
      { event: 'Quarterback Hits', range: '1-10', points: '0.5 points each' },
      { event: 'Safeties', range: '1-10', points: '5 points each' },
      { event: 'Offensive Points Against', range: '0-0', points: '5' },
      { event: 'Passing Yards Allowed', range: '-99-0', points: '5' },
      { event: 'Passing Yards Allowed', range: '1-999', points: '-0.01 points each' },
      { event: 'Rushing Yards Allowed', range: '-99-0', points: '5' },
      { event: 'Rushing Yards Allowed', range: '1-999', points: '-0.02 points each' },
      { event: 'Number of Defensive TDs', range: '1-10', points: '6 points each' },
      { event: 'Opponent Penalty First Downs', range: '1-99', points: '-0.5 points each' },
      { event: 'Opponent Fourth Downs Failed', range: '1-99', points: '1.5 points each' },
    ],
  },
]

// Every group except Head Coach/Offensive Coordinator/Defensive
// Coordinator scores for whichever roster player actually recorded the
// event, regardless of their primary position.
export const UNIVERSAL_TAGS = RULE_GROUPS.filter((g) => !g.independent).map((g) => g.tag)
export const INDEPENDENT_TAGS = RULE_GROUPS.filter((g) => g.independent).map((g) => g.tag)

// Legal starting lineup composition -- the top three rows are two single-
// count slots side by side, the rest are one full-width row each.
export const STARTING_LINEUP_ROWS = [
  [{ label: 'Head Coach (HC)' }, { label: 'Quarterback (QB)' }],
  [{ label: 'Defense (Def)' }, { label: 'Offense (ST)' }],
  [{ label: 'Kicker (PK)' }, { label: 'Punter (PN)' }],
  [{ label: 'IDP/Skill', value: '0-10' }],
  [{ label: 'Reserve', value: '5' }],
  [{ label: 'IR', value: '2' }],
]

// Roster (not just starting-lineup) position count limits.
export const ROSTER_LIMITS = [
  { position: 'Coach', range: '1-2' },
  { position: 'QB', range: '1-2' },
  { position: 'RB', range: '0-4' },
  { position: 'FB', range: '0-2' },
  { position: 'WR', range: '0-4' },
  { position: 'TE', range: '0-3' },
  { position: 'PK', range: '1-2' },
  { position: 'PN', range: '1-2' },
  { position: 'DT', range: '0-3' },
  { position: 'DE', range: '0-3' },
  { position: 'LB', range: '0-4' },
  { position: 'CB', range: '0-3' },
  { position: 'S', range: '0-3' },
  { position: 'Def', range: '1-2' },
  { position: 'ST', range: '1-2' },
]
